"""
streamrelay.producer — Send tokens from an HPC compute node to a relay.

This module is designed to run INSIDE a Globus Compute function executing on
an HPC cluster. It connects outbound to the relay server and forwards tokens
as they are generated by an LLM (or any other streaming source).

Both sides connect outbound to the relay — no inbound ports needed, no VPN,
no SSH tunnels. This works even behind strict campus firewalls.

Usage::

    from streamrelay import RelayProducer

    def my_globus_function(relay_url, channel_id, encryption_key=""):
        producer = RelayProducer(relay_url, channel_id, encryption_key)
        with producer:
            for token in your_model_stream(prompt):
                producer.send_token(token)
            producer.send_done()

.. note::
    This module uses the **synchronous** ``websockets`` API (``websockets.sync``)
    because Globus Compute functions are plain Python functions, not async.
"""

import json
import logging

logger = logging.getLogger(__name__)


class RelayProducer:
    """
    WebSocket producer that sends tokens to a relay channel.

    Designed for use inside Globus Compute remote functions where async is
    not available. Uses ``websockets.sync.client`` for blocking I/O.

    Args:
        relay_url: WebSocket URL of the relay server, e.g. ``ws://relay.example.com:8765``.
        channel_id: Unique channel identifier (UUID). Must match the consumer's channel_id.
        encryption_key: Optional base64-encoded 32-byte AES-256 key. When set, every
            message is encrypted with AES-256-GCM before being sent to the relay,
            so the relay server itself cannot read the token content.
        relay_secret: Optional shared secret for relay authentication. Must match the
            relay server's ``--secret`` flag.
    """

    def __init__(
        self,
        relay_url: str,
        channel_id: str,
        encryption_key: str = "",
        relay_secret: str = "",
    ):
        self.relay_url = relay_url.rstrip("/")
        self.channel_id = channel_id
        self.encryption_key = encryption_key
        self.relay_secret = relay_secret
        self._ws = None

    # ------------------------------------------------------------------
    # Context-manager support: ``with RelayProducer(...) as p:``
    # ------------------------------------------------------------------

    def __enter__(self):
        self.connect()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type is not None:
            try:
                self._send_raw({"type": "error", "message": f"{exc_type.__name__}: {exc_val}"})
                self._send_raw({"type": "done"})
            except Exception:
                pass
        else:
            try:
                self.send_done()
            except Exception:
                pass
        self.close()
        return False  # don't suppress exceptions

    async def __aenter__(self):
        """Async context manager: ``async with RelayProducer(...) as p``."""
        from websockets.asyncio.client import connect as ws_connect

        url = f"{self.relay_url}/produce/{self.channel_id}"
        if self.relay_secret:
            url += f"?secret={self.relay_secret}"
        self._ws_cm = ws_connect(url)
        self._ws = await self._ws_cm.__aenter__()
        logger.debug(f"[streamrelay] async producer connected: channel={self.channel_id[:8]}")
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if exc_type is not None:
            try:
                await self._async_send_raw({"type": "error", "message": f"{exc_type.__name__}: {exc_val}"})
                await self._async_send_raw({"type": "done"})
            except Exception:
                pass
        else:
            try:
                await self._async_send_raw({"type": "done", "usage": {}})
            except Exception:
                pass
        await self._ws_cm.__aexit__(exc_type, exc_val, exc_tb)
        self._ws = None
        return False

    async def _async_send_raw(self, payload: dict):
        """Async version of _send_raw for use in async context manager."""
        raw = json.dumps(payload)
        if self.encryption_key:
            from streamrelay.crypto import encrypt_message
            raw = encrypt_message(self.encryption_key, raw)
        await self._ws.send(raw)

    # ------------------------------------------------------------------
    # Connection management
    # ------------------------------------------------------------------

    def connect(self):
        """Open the WebSocket connection to the relay as a producer."""
        from websockets.sync.client import connect as ws_connect

        url = f"{self.relay_url}/produce/{self.channel_id}"
        if self.relay_secret:
            url += f"?secret={self.relay_secret}"
        self._ws = ws_connect(url)
        logger.debug(f"[streamrelay] producer connected: channel={self.channel_id[:8]}")

    def close(self):
        """Close the WebSocket connection."""
        if self._ws is not None:
            try:
                self._ws.close()
            except Exception:
                pass
            self._ws = None

    # ------------------------------------------------------------------
    # Sending
    # ------------------------------------------------------------------

    def _send_raw(self, payload: dict):
        """Serialize, optionally encrypt, and send a dict over the WebSocket."""
        if self._ws is None:
            raise RuntimeError("RelayProducer is not connected. Call connect() first.")
        raw = json.dumps(payload)
        if self.encryption_key:
            from streamrelay.crypto import encrypt_message
            raw = encrypt_message(self.encryption_key, raw)
        self._ws.send(raw)

    def send_token(self, content: str):
        """Send a single token (text chunk) to the relay.

        Args:
            content: The token text, e.g. ``"Hello"`` or ``" world"``.
        """
        self._send_raw({"type": "token", "content": content})

    def send_done(self, usage: dict | None = None):
        """Signal that generation is complete.

        Args:
            usage: Optional dict with token usage stats, e.g.
                ``{"prompt_tokens": 10, "completion_tokens": 50, "total_tokens": 60}``.
        """
        self._send_raw({"type": "done", "usage": usage or {}})

    def send_error(self, message: str):
        """Send an error message to the relay (consumer will see it in logs).

        Also sends a ``done`` signal so the consumer is not left waiting.

        Args:
            message: Human-readable error description.
        """
        self._send_raw({"type": "error", "message": message})
        self._send_raw({"type": "done"})
