name: JOSS Paper

on:
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Compile JOSS paper
    steps:
      - uses: actions/checkout@v4

      - name: Build draft PDF
        uses: docker://openjournals/inara
        with:
          args: -p -o pdf paper/paper.md

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper/paper.pdf
